#!/usr/bin/env python3
"""§17.431 — one-time migration: add Milvus 2.5 native BM25 to toon_v2.

Milvus BM25 Functions are defined at COLLECTION-CREATION time, so adding the
sparse field + Function to an existing collection requires recreate + re-ingest
(the dense vectors are preserved verbatim on re-insert; the BM25 sparse vector
is auto-generated from canonical_text by the Function). This is OPERATOR-RUN
and mutates the live knowledge base, so it is dry-run by default and writes a
full JSON backup of every row BEFORE dropping anything.

Sequence (with --apply):
  1. dump all rows (all 16 fields incl dense_vector) by fanning out per domain
     (partition-key isolation rejects unfiltered queries)
  2. write the dump to a backup file and verify the count
  3. drop the collection
  4. recreate it with the BM25 schema (build_toon_v2_schema(bm25=True))
  5. re-insert all rows in batches (sparse_bm25 is generated by the Function;
     do NOT supply it)
  6. flush + load + verify the re-inserted count matches the dump

Then set rag_bm25_enabled=True (env RAG_BM25_ENABLED) and restart so
_keyword_search routes through BM25.

Usage:
  # dry run against the real collection (no mutation):
  python scripts/migrate_toon_v2_bm25.py
  # actually migrate:
  python scripts/migrate_toon_v2_bm25.py --apply
  # test the whole flow on a throwaway collection:
  python scripts/migrate_toon_v2_bm25.py --collection _bm25_migrate_test --apply
  # restore from a backup if a re-insert ever fails:
  python scripts/migrate_toon_v2_bm25.py --from-backup <file.json> --apply
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

from pymilvus import MilvusClient

from app.config import settings, VALID_DOMAINS
from app.utils.milvus_utils import (
    BM25_SPARSE_FIELD,
    build_toon_v2_index_params,
    build_toon_v2_schema,
)

# The 16 persisted fields (everything except the generated sparse vector).
DUMP_FIELDS = [
    "entry_id", "title", "canonical_text", "domain", "domain_tags",
    "confidence_score", "source_type", "source_url", "content_hash",
    "model_id", "version", "supersedes_id", "created_at", "updated_at",
    "expires_at", "dense_vector",
]


def _has_bm25(client: MilvusClient, name: str) -> bool:
    desc = client.describe_collection(name)
    fields = {f.get("name") for f in desc.get("fields", [])}
    return BM25_SPARSE_FIELD in fields


def _normalize(r: dict) -> dict:
    """Coerce Milvus protobuf containers to JSON-native lists (so the backup
    serializes and the re-insert gets plain python types)."""
    out = dict(r)
    if out.get("dense_vector") is not None:
        out["dense_vector"] = [float(x) for x in out["dense_vector"]]
    if out.get("domain_tags") is not None:
        out["domain_tags"] = [str(x) for x in out["domain_tags"]]
    return out


def dump_all(client: MilvusClient, name: str) -> list[dict]:
    """Fan out per domain (partition-key isolation) and collect every row."""
    rows: list[dict] = []
    for d in sorted(VALID_DOMAINS):
        it = client.query_iterator(
            collection_name=name,
            filter=f'domain == "{d}"',
            output_fields=DUMP_FIELDS,
            batch_size=500,
        )
        while True:
            batch = it.next()
            if not batch:
                it.close()
                break
            rows.extend(_normalize(x) for x in batch)
    return rows


def reinsert(client: MilvusClient, name: str, rows: list[dict], batch: int) -> int:
    inserted = 0
    for i in range(0, len(rows), batch):
        chunk = [{k: r[k] for k in DUMP_FIELDS if k in r} for r in rows[i:i + batch]]
        client.insert(collection_name=name, data=chunk)
        inserted += len(chunk)
        print(f"  inserted {inserted}/{len(rows)}")
    return inserted


def main() -> int:
    ap = argparse.ArgumentParser(description="Migrate toon_v2 to BM25 (§17.431)")
    ap.add_argument("--collection", default="toon_v2")
    ap.add_argument("--apply", action="store_true", help="actually migrate (default dry-run)")
    ap.add_argument("--backup-file", default="")
    ap.add_argument("--from-backup", default="", help="restore rows from this JSON instead of dumping")
    ap.add_argument("--batch-size", type=int, default=200)
    args = ap.parse_args()

    client = MilvusClient(settings.milvus_uri)
    name = args.collection

    if args.from_backup:
        rows = json.loads(Path(args.from_backup).read_text())
        print(f"loaded {len(rows)} rows from backup {args.from_backup}")
    else:
        if not client.has_collection(name):
            print(f"ERROR: collection {name!r} does not exist", file=sys.stderr)
            return 2
        if _has_bm25(client, name):
            print(f"{name!r} already has {BM25_SPARSE_FIELD!r} — already migrated, nothing to do.")
            return 0
        print(f"dumping all rows from {name!r} (per-domain fan-out)…")
        rows = dump_all(client, name)
        print(f"dumped {len(rows)} rows")
        # Default to /tmp — the app user can't write /code. Operators wanting a
        # persistent backup should pass --backup-file pointing at a mounted volume.
        backup = args.backup_file or f"/tmp/toon_v2_bm25_backup_{int(time.time())}.json"
        Path(backup).write_text(json.dumps(rows))
        print(f"backup written: {backup} ({len(rows)} rows)")

    if not args.apply:
        print("\nDRY RUN — no mutation. Re-run with --apply to migrate.")
        print(f"  would: drop {name!r} → recreate with BM25 schema → re-insert {len(rows)} rows")
        return 0

    print(f"dropping {name!r}…")
    if client.has_collection(name):
        client.drop_collection(name)
    print("recreating with BM25 schema…")
    client.create_collection(
        collection_name=name,
        schema=build_toon_v2_schema(bm25=True),
        index_params=build_toon_v2_index_params(client, bm25=True),
        num_partitions=settings.milvus_num_partitions,
        properties={"partitionkey.isolation": "true"},
    )
    print(f"re-inserting {len(rows)} rows…")
    n = reinsert(client, name, rows, args.batch_size)
    client.flush(name)
    client.load_collection(name)

    stats = client.get_collection_stats(name)
    print(f"\nDONE: re-inserted {n} rows; collection row_count={stats.get('row_count')}")
    if n != len(rows):
        print(f"WARNING: inserted {n} != dumped {len(rows)} — investigate before deleting the backup", file=sys.stderr)
        return 1
    print("Next: set RAG_BM25_ENABLED=true and restart the orchestrator.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
